# Generated by Django 3.2.23 on 2023-11-15 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('likes', '0001_initial'),
        ('community', '0002_alter_community_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='like',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='likes.like'),
        ),
    ]
